### ISSUE TITLE
[QUESTION] Property decorator is deprecated for some overload definitions

### ISSUE THREAD

**Issue by silveoj** [TypedProject/tsed#1001]
tsed v. 5.65.3

EsLint shows me `@Property()` (without parameter) from  `'@tsed/common';` is deprecated.
- Do we need now to use `'@tsed/schema';`? - It's good news. But doc is less than for `common`
- Or do we need to pass `type: Type<any>` or `options?: IPropertyOptions | string | Type<any>`? - I can't find examples for it
- `@Property(options) is deprecated. Use @Name() or/and @CollectionOf() instead` - Or do we need to use `@Name`?

```
  // my current code
  @Property()
  public id: number;
```
Is it correct alternative?
```
  @Name(Nmber)
  public id: number;
```
Thanks

**Comment by Romakita** [comment]
Hello @silveoj 
For v5 user the @tsed/schema cannot be used because it’s a prerelease for the v6.

Your alternative is wrong, Name decorator must be used to change the property name on serialization/deserialization. You don’t need to set the Number type a parameter. TsED infer automatically this type from typescript metadata. 

You shouldn’t have deprecated note for the Property decorator for your current code. If you have a warning, is not normal and I need to fix it.
See you

**Comment by silveoj** [comment]
```
import { Property } from '@tsed/common';

// ...

  @Property()
  public id: number;
```

I get warning: Deprecated. eslint(import/no-deprecated)
(`"import/no-deprecated": "warn",`) (eslint 7.10.0)

`node_modules\@tsed\common\lib\jsonschema\decorators\property.d.ts`
```
export declare function Property(options?: IPropertyOptions | string | Type<any>): Function;
export declare function Property(type: Type<any>): PropertyDecorator;
/**
 * @deprecated
 */
export declare function Property(options: IPropertyOptions): PropertyDecorator;
/**
 * @deprecated
 */
export declare function Property(name: string): PropertyDecorator;
```
I don't pass parameter so it's first function with optional `options`. But I have warning.

v 5.65.3 - 5.65.7

**Comment by Romakita** [comment]
Ok I'll fix this issue :)

**Comment by Romakita** [comment]
There is other decorators with the same kind of issue ?

**Comment by silveoj** [comment]
I had issue/question with ```@Middleware()```. But I fixed it.

Server started but I can't login:  `Class constructor MyMiddleware cannot be invoked without 'new'`
```
// didn't work
export function myMiddleware (myFutureParam) { // closure for additional param just in case
  @Middleware()
  class MyMiddleware implements IMiddleware {
    public use(@Request() request, @Next() next: Express.NextFunction) {
      // ...
      next();
    }
  }

  return MyMiddleware;
}
// ...
public $beforeRoutesInit(): void | Promise<any> {
    this.use(myMiddleware()) // it was called each request
```
```
// works with any version
@Middleware()
class MyMiddleware implements IMiddleware {
  public use(@Request() request, @Next() next: Express.NextFunction) {
    // ...
    next();
  }
}
// ...
public $beforeRoutesInit(): void | Promise<any> {
    this.use(MyMiddleware)
```
Closure approach always works for controller middlewares. But not in `app.use` place. So I add field:
```
private myConst = myMiddleware(); // works
public $beforeRoutesInit(): void | Promise<any> {
   const myConst = myMiddleware(); // doesn't work
    this.use(myConst)
```

**Comment by Romakita** [comment]
Hum ... because you cannot instanciate your middleware manually and give the instance to use function. Express.js waiting a pure function, Ts.ED create a pure function when it's Ts.ED middleware and map request/response/parameters to the `use` method.

The workaround is to use a arrow function and map manually the parameters.

**Comment by Romakita** [comment]
The fix is released.

**Comment by silveoj** [comment]
Thanks.
Now `@Property()` is not deprecated.
Also arrow function is workaround in `app.use`.
