### ISSUE TITLE
[BUG] Page Introduction - /response example  structure/

### ISSUE THREAD

**Issue by angelquin1986** [TypedProject/tsed#1089]
"examples" type  no  this into "content"-> "application/json" .
The source
![image](https://user-images.githubusercontent.com/32068691/99114948-ab6d9980-25bf-11eb-8df3-ca5a7e1a9b1a.png)
The error swagger json 
![image](https://user-images.githubusercontent.com/32068691/99115063-da840b00-25bf-11eb-8132-5cb84e4a14e1.png)
The correc swagger json
![image](https://user-images.githubusercontent.com/32068691/99115243-1919c580-25c0-11eb-9819-cf7a4fe52863.png)

**Comment by Romakita** [comment]
Hello,
It's a good issue for new contributors.
The problem is located in this file:
https://github.com/TypedProject/tsed/blob/production/packages/schema/src/decorators/operations/returns.ts#L397

The mapping is here: 
https://github.com/TypedProject/tsed/blob/production/packages/schema/src/decorators/operations/returns.ts#L128

Example must be added to the media level and not on the response level.

We need to update the JsonMedia model by adding `examples` method: 
https://github.com/TypedProject/tsed/blob/production/packages/schema/src/domain/JsonResponse.ts#L12

## Acceptance criteria

- [ ] OS3 is correctly generated
- [ ] OS2 is correctly generated
- [ ] Integration test are up-to-date

**Comment by Romakita** [comment]
@LorianeE This issue is designed for you ;)
