### ISSUE TITLE
[BUG] Incorrect JSON Schema Generated When Combining @Schema Decorator, oneOf, and @QueryParams

### ISSUE THREAD

**Issue by ecalvert** [TypedProject/tsed#1262]
## Information

- **Version:** 6.27.0

When using a model that has a property decorated with `@Schema({ oneOf: [ { type: 'string' }, { type: 'number' }  ] })` the items in the `oneOf` array will are duplicated for each controller in your app.

## Example
```ts
// ObjectIDCollection.ts

const pattern = '^[a-fA-F\\d]{24}$'

export function ObjectIDCollection () {
  return useDecorators(
    Schema({
      oneOf: [
        {
          type: 'string',
          pattern,
        },
        {
          type: 'array',
          items: {
            type: 'string',
            pattern,
          },
        },
      ],
    }),
  )
}
```

```ts
// HelloWorldController.ts

export class Thing {
  @Default(0)
  skip: number

  @Default(50)
  @Maximum(50)
  limit: number

  @ObjectIDCollection()
  badSchema: string[]
}

@Controller("/hello-world")
export class HelloWorldController {
  @Get("/")
  @Returns(200, String)
  get(@QueryParams(Thing) params: Thing) {
    return 'hello'
  }
}

```

```ts

// FooController.ts

import {Controller, Get } from "@tsed/common";
import { Returns } from "@tsed/schema";

@Controller("/foo")
export class FooController {
  @Get("/")
  @Returns(200, String)
  get() {
    return 'foo'
  }
}

```

If you look at the generated `v3/docs/swagger.json` file, the `badSchema` parameter has 4 entries in the oneOf property:

```json
{
  "in": "query",
  "required": false,
  "name": "badSchema",
  "schema": {
    "oneOf": [
      {
        "type": "string",
        "pattern": "^[a-fA-F\\d]{24}$"
      },
      {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^[a-fA-F\\d]{24}$"
        }
      },
      {
        "type": "string",
        "pattern": "^[a-fA-F\\d]{24}$"
      },
      {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^[a-fA-F\\d]{24}$"
        }
      }
    ]
  }
}
```

If you remove the FooController, the schema is correct.

I threw together a repo that re-creates the issue:
https://github.com/ecalvert/tsed-anyof

**Comment by Romakita** [comment]
Hello @ecalvert 
It's not a bug for me. This is because you trying to complicate the schema when there is no need for it with a QueryParameter.

QueryParameters can be always a string or string[]. Swagger doesn't known how to render this usecase and display only a textfield (for me it's not correct):

```typescript
      parameters:
        - in: query
          name: env
          required: false
          schema:
            oneOf:
              - type: string
              - type: array
                items: 
                  type: string
```
<img width="1382" alt="Capture d’écran 2021-03-05 à 08 25 55" src="https://user-images.githubusercontent.com/1763311/110081602-72cf1700-7d8c-11eb-819d-1329bd1af99e.png">

The good way is to describe the query parameter as string[]:

```
export class Thing {
  @Default(0)
  skip: number

  @Default(50)
  @Maximum(50)
  limit: number

  @Pattern('^[a-fA-F\\d]{24}$')
  @CollectionOf(String)
  badSchema: string[]
}
```
<img width="457" alt="Capture d’écran 2021-03-05 à 08 27 42" src="https://user-images.githubusercontent.com/1763311/110081769-b6c21c00-7d8c-11eb-9de7-ca77e481dedb.png">

This solution works both for string and string[] and Ts.ED will handle correctly your queryparams in both case.

See you
Romain
