### ISSUE TITLE
[QUESTION] v6 Migration - Mongoose array keys are string instead of number

### ISSUE THREAD

**Issue by royibernthal** [TypedProject/tsed#1290]
Since migrating to v6, the mongoose array returns array keys as string instead of number.

For instance, I have the following field in my model:

```
@Ref(Gender)
interests: string[];
```

Let's say it contains the following values (which will be valid object ids in reality): `['a', 'b', 'c']`

When logging it via $log, it appears to be a normal array: `['a', 'b', 'c']`

However, when sending it in a response, I'm getting the following:

```
{
	'0': 'a',
	'1': 'b',
	'2': 'c'
}
```

If I iterate over interests manually and convert the keys to numbers it solves the issue:

```
private convertArray(value: any[]) {
        const result: string[] = [];

        for (let key in value) {
            result[ Number(key) ] = value[key];
        }

        return result;
    }
```

Any idea why it happens and how it can be avoided? In v5 it used to work as expected, the array keys were numbers.

**Comment by Romakita** [comment]
Try:
```
@Ref(Gender)
interests: Ref<Gender>[];
```

**Comment by royibernthal** [comment]
@Romakita Just did, same result.

**Comment by Romakita** [comment]
I need a repo with a reproducible example. This case is covered by unit test on the framework and it works.

see you
Romain

**Comment by royibernthal** [comment]
Hey Romain,

Sure, here you go:
https://github.com/royibernthal/tsedrepro

**POST http://localhost:8083/rest/create**

```
{
    "id": "6052deeff1b351725c63433b",
    "name": "user_8267460602",
    "interests": {
        "0": "6052deeff1b351725c63433a"
    }
}
```

**Comment by Romakita** [comment]
PR  https://github.com/royibernthal/tsedrepro/pull/1

**Comment by Romakita** [comment]
The issue is about mongoose and the new json-mapper. You have to use `@Returns` decorator to instrument correctly the json-mapper. Mongoose doesn't return the expected class (it's a wrapper of the original Class), and unfortunately, it's doesn't works correctly with json-mapper without the decorator.

See you
Romain

**Comment by Romakita** [comment]
After investigation. The `@returns` decorator isn't mandatory if your return the user mongoose instance. But You map the user to a raw object, the problem occurs:

Doesn't works:
```typescript
return {
      id: user._id,
      interests: user.interests
}
```

**Comment by Romakita** [comment]
PR https://github.com/TypedProject/tsed/pull/1293

But, I encourage you to use the `@Returns` decorator and limit the usage of raw object to map data. Ts.ED has Groups strategy now to Map properties depending on the endpoint.

See you

**Comment by royibernthal** [comment]
Thanks for uploading a fix.
Will it take it some time to become available? The latest tsed version available at the moment as far as I can see (which I have installed) is 6.34.1.

In my actual project I'm never returning the actual mongoose model, as I need to play a little with the data, so I'll always be mapping it.

To make sure we're on the same page - the repro version with mapping doesn't work even with the `@Returns` decorator, at least before the fix. Is it expected to?

Since I don't really need documentation at the moment, how basic can my Return decorator be to properly handle just the mapping? Can it be empty? i.e. `@Returns()`

**Comment by royibernthal** [comment]
I just updated to 6.34.2. Indeed solved, much appreciated :)

Could you please shed some more light on the `@Return` decorator and how it's relevant to mapping?

From your documentation it appears to be solely related to creating documentation:
https://tsed.io/api/schema/decorators/operations/Returns.html#decorator-returns

Would using an empty `@Returns` deocrator allow me to leverage tsed's groups strategy?

**Comment by Romakita** [comment]
Returns is used by json-mapper to know exactly which class you want to use to serialize the response. In most case, the type is inferred by the return object itself. 

It's just a good practice to use it ;)

Usage with groups:

```typescript
import {BodyParams, Controller, Get, PathParams, Post} from "@tsed/common";
import {Groups, Returns} from "@tsed/schema";
import {User} from "../models/User";

@Controller("/")
export class UsersCtrl {
  @Get("/:id")
  @Returns(200, User).Groups("group.*")
  async get(@PathParams("id") id: string) {
  }

  @Post("/")
  @Returns(201, User).Groups("group.*")
  async post(@BodyParams() @Groups("creation") user: User) {
    console.log(user); // User {firstName, lastName, email, password}
    user.id = uuid();

    return user;  // will return Object {id, firstName, lastName, email}
  }
}
```

**Comment by royibernthal** [comment]
1) So just to make sure I understand you correctly - simply stating an empty `@Returns()` will help json-mapper as well since the type will be inferred anyway by the return object itself in most cases. Is that correct?
If so, why not apply a default `@Returns()` to all endpoints under the hood in case no custom `@Returns` was specified?

2) Does `@Returns` only help json-mapper avoid mapping mistakes or does it also make mapping faster? (or are groups responsible for making mapping faster?)

3) Should I use multiple `@Returns` statements for all errors that can possibly be thrown by an endpoint as well or is that redundant (assuming I don't need documentation)?

For instance:
```
@Returns(200)
@Returns(400)
@Returns(500)
```

4) What if my response is an interface and not a mongoose model? Since an interface isn't compiled, I can't really pass it to the decorator as an object.
Am I supposed to create a class instead of an interface for that?

i.e.

```
class CustomResponse {
  id: string;
  name: string;
  interests: string[];
}
```

`@Returns(201, CustomResponse)`

5) Is there anywhere I could read more about groups?

Royi

**Comment by Romakita** [comment]
1) No, empty Returns does nothing. But give a type as follow `@Returns(200, MyClass)` helps the json-mapper to use the correct class for each field. But by default is not mandatory, I think with your latest feedback, json-mapper are able to infer correctly the type for the return value (and his props).  


2) Yes, the Returns decorator help `json-mapper` to avoid mapping mistakes by using the exact type from TypeScript metadata. The mapping is also simplified for the developer because, the mapping is based on the class and his props metadata. By using groups, Ts.ED will only map the expected props.

3) If you don't care about documentation, isn't necessary. But, I encourage you to use Swagger is a very useful tool to test your API manually and to have a quick overview of your contract services :). There is no high cost to maintain it with the Ts.ED decorator and consumers can use it to generate client (or just test you api).

4) Interface cannot be used to serialize object. Again, use this decorator isn't necessary in most case. My point is, I prefer to use Returns when I return a class or a collection of class to avoid mapping mistake (but I think with your last feedback the json-mapper v6 is now stable :) )

So you don't need to create class ;)

5) Sure, here is the documentation: https://tsed.io/docs/model.html#groups

**Comment by royibernthal** [comment]
Thanks for the detailed answers :)

**Comment by Romakita** [comment]
Your welcome ;)
