### ISSUE TITLE
[BUG] VirtualRef not setting justOne

### ISSUE THREAD

**Issue by LFSousa** [TypedProject/tsed#1299]
## Information

- **Version:** 6.34.3
- Packages: mongoose

The schema not reflects the justOne argument setted on VirtualRef when using VirtualRefs, so I can't show more than one reference like a list

### Not works:
```ts
  @VirtualRef({
    type: Student,
    foreignField: "uuid",
    localField: "studentUuids",
  })
  students?: VirtualRefs<Student>;
```

### Works:
```ts
  @VirtualRef({
    type: Student,
    foreignField: "uuid",
    localField: "studentUuids",
  })
  students?: VirtualRef<Student>[];
````
## Acceptance criteria

- [ ] justOne needs to be reflected at schema when use VirtualRefs

**Comment by Romakita** [comment]
Hello @LFSousa 
The justOne option seems to be mapped: 
https://github.com/TypedProject/tsed/blob/production/packages/mongoose/src/decorators/virtualRef.ts

but I think the problem is here:
https://github.com/TypedProject/tsed/blob/production/packages/mongoose/src/utils/createSchema.ts#L116

I don’t know why is written as it ^^. Can you just edit the js in node_module and remove this line. Tell me if it works ;) then I’ll create a PR.

see you
Romain

**Comment by LFSousa** [comment]
It works perfectly! Just remove the line.

**Comment by Romakita** [comment]
Ok great I’ll fix that ASAP
