### ISSUE TITLE
[BUG/QUESTION] Passport.js returning jwt payload on void endpoint

### ISSUE THREAD

**Issue by LFSousa** [TypedProject/tsed#1318]
## Information

- **Version:** 6.3.11
- Packages: passport

When I make a request to an authenticated endpoint over jwt, the response is always my decoded jwt payload.
How can I fix this without need to return something on my endpoint?

## Example

```typescript
@Protocol<StrategyOptions>({
  name: "jwt",
  useStrategy: Strategy,
  settings: {
    jwtFromRequest: ExtractJwt.fromAuthHeaderAsBearerToken(),
    secretOrKey: process.env.JWT_SECRET || "",
  },
})
export class PassportJwtProtocol implements OnVerify {
  async $onVerify(@Arg(0) jwtPayload: any) {
    return jwtPayload;
  }
}

export function Authenticated() {
  return useDecorators(Authenticate("jwt"), Status(401).Description("Unauthorized"));
}

```
```typescript
@Post("/endpoint")
@Returns(200)
@Authenticated()
async endpoint() {}

```

**Comment by Romakita** [comment]
The verify method shouldn’t be called if you are authenticated… so it mean you call your endpoint without token.

**Comment by Romakita** [comment]
And by convention empty response should send a 204 ;)

**Comment by derevnjuk** [comment]
@Romakita don't you think that... looks quite strange. You mentioned a good example with 204 status response, but what about 201 which may be used with `Location` header? I think   `OnVerify` implementations should have different behavior from middleware. Otherwise, it might lead to unexpected behavior and security breaches as soon as someone sets wrong or omits `Response` decorator.
