### ISSUE TITLE
[Bug] Primitive type declared as object in swagger

### ISSUE THREAD

**Issue by tomer-amir** [TypedProject/tsed#424]
## Information

Type | Version
---|---
Bug | 4.x

****

## Description
I am trying to build a simple for endpoint with a boolean variable:
```typescript
	@Post('/test')
	@Operation({ consumes: ['application/x-www-form-urlencoded'] })
	test(@BodyParams() par1: boolean) {
		// code ...
	}
```

And here is the resulting swagger:
```yaml
paths:
  /api/test:
    post:
      operationId: TestCtrl.test
      parameters:
        - in: body # <--- this is wrong
          name: body # <--- this is wrong
          required: false
          schema:
            $ref: '#/definitions/Boolean' # <--- this is wrong
      consumes:
        - application/x-www-form-urlencoded
```
Expected:
```yaml
paths:
  /api/test:
    post:
      operationId: TestCtrl.test
      parameters:
        - in: formData # <--- expected
          name: par1
          required: false
          type: boolean # <--- expected
      consumes:
        - application/x-www-form-urlencoded
```

Thanks!

## Acceptance criterias

- [ ] Example (log, usecase, etc...)
- [ ] Ts.ED version (bug/question)

**Comment by TomerAmirV** [comment]
Hi!
any news?

**Comment by Romakita** [comment]
Hello @TomerAmirV,

Sorry, currently I try to fix all bug related to JsonSchema and Swagger. It's big works.

Other things, your configuration is a bit strange, because the SwaggerService will not understand you trying to create multipart formdata. Normaly, the MultipartFile is used to change the behavior of SwaggerService. 

To allow your needs, we need to create a new decorator or change the SwaggerService (note: Consumes decorators already exists)

It can be fixed on this file:
https://github.com/Romakita/ts-express-decorators/blob/master/src/swagger/class/OpenApiParamsBuilder.ts#L28

With this code:
```typescript

  constructor(target: Type<any>, methodClassName: string, private pathParameters: PathParameter[] = []) {
    super(target);
    this.name = `${nameOf(target)}${methodClassName.charAt(0).toUpperCase() + methodClassName.slice(1)}`;

    this.injectedParams = ParamRegistry.getParams(target, methodClassName).filter(param => {
      if (param.paramType === ParamTypes.BODY) {
        this.hasBody = true;
      }

      if (param.paramType === ParamTypes.FORM_DATA) {
        this.hasFormData = true;
      }

      return !param.store.get("hidden");
    });

   const operation = Store.fromMethod(target, methodClassName).get('operation') || {};
   if (operation.consumes && operation.consumes.indexOf('application/x-www-form-urlencoded')) {
       this.hasFormData = true;
   }
}
````
> If something can test and create PR, it help me a lot.

For the second bug on Boolean, It's one of the story related to JsonSchema and I work on.

See you,
Romain

**Comment by TomerAmirV** [comment]
Thanks!
Waiting for updates 😄
