### ISSUE TITLE
Ask question about swagger

### ISSUE THREAD

**Issue by TranBaVinhSon** [TypedProject/tsed#651]
## Information

- **Version:** 5.x
- **Type:** Issue/Story

## Description
I want to make sure the client sent a hash as a param of `GET` request. So I use this syntax `@Get("/(:templateHash*)?")` . But I notice that my swagger have double API `GET`?

<img width="1452" alt="Screen Shot 2019-09-24 at 19 25 17" src="https://user-images.githubusercontent.com/12994069/65504005-1746fb80-df01-11e9-9e1b-b1fdf4a69042.png">
 

And instead of `@Get("/(:templateHash*)?")`, I use `@Get("/:templateHash")`. But I couldn't check  whether the client sends me a hash or not.
If the client doesn't send me a hash, I will return `400` error instead of this body

<img width="1055" alt="Screen Shot 2019-09-24 at 19 26 19" src="https://user-images.githubusercontent.com/12994069/65504065-36de2400-df01-11e9-9a06-280d7cad9a8c.png">

```ts
  @Get("/:templateHash")
  @ContentType("application/json")
  @Returns(200, { description: "Find template and return template's binary" })
  @Returns(400, { description: "Didn't set template hash" })
  @Returns(404, { description: "Can't find template in DB with template hash" })
  @Summary("Get template file")
  async get(@PathParams("templateHash") templateHash: string) {
    console.log("templateHash", templateHash); // I can't access this when client doesn't send me a hash. It should return undefined or null
  }

```

Any advice is welcome!

**Comment by Romakita** [comment]
Hello @TranBaVinhSon 
Yes I can said directly, isn't supported, because I never see this glob pattern before :) and swagger understand only basic path with brackets. So the swagger builder convert express path to swagger path with a basic support.

The code responsible to convert this path is here: https://github.com/TypedProject/ts-express-decorators/blob/master/packages/swagger/src/utils/index.ts#L6

I don't written this code so is a bit obscur for me. If you have a better solution or a quick fix (PR) for me, I'll take it :)

See you
Romain
