### ISSUE TITLE
Converter, Validation and Swagger

### ISSUE THREAD

**Issue by chiqui3d** [TypedProject/tsed#794]
## Informations
**Is your feature request related to a problem? Please describe.**

The problem I've had and I'm sure many people have had it. 
is that Swagger should be completely isolated from the `converter and validation`.
Swagger should not interfere with the validation and conventer.

I realized that in an entity with only put the swagger description in a `property `is already validated and serializing my full `entity`, that can not be.

`Swagger `is just a control panel, I can have it activated for testing while I perform my frontend, but `the use or not` of swagger, I will need a validation and converter, and not depend on it.

**Describe the solution you'd like**

Separate/migrate in a package `@tsed/validator or @tsed/serialize` or really the right name, independently of `swagger`, the `swagger `package should only have what is related to the panel, I think, I don't know if I am wrong.

**Describe alternatives you've considered**

Another option although I don't have it very clear, I would have to see other packages to see how they do it, is to put the `@Serialize()` or` @Expose()` or `@TSED` property in the class and not need the @Property() decorator, that is to say with putting the @Serialize decorator I would already be completely using the converter/transformer/validator, depending already on the decorators that you put. That is to say, I could have this:

```ts
@Serialize()
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number

    @MinLength(5)
    @Required()
    @Column()
    username: string

    @Email()
    @Column()
    email: string

    @IgnoreProperty()
    @Column()
    password: string
}
```

```ts
@Serialize()
@Entity()
export class User {

    @PrimaryGeneratedColumn()
    id: number

    @Column()
    username: string

    @Column()
    email: string

    @IgnoreProperty()
    @Column()
    password: string
}
```

In this last case, it is returning the full class ignoring the password. Like the previous one, but without the need of other decorators and without Swagger intervening if you put a description or not.

## Update: 

Well actually the decorator at the top of the class wouldn't be necessary either, if I'm already telling you at the controller...
**I think the only thing was the Swagger thing that interfered when I was just trying to validate and convert.**

Other request Serialize Group:
https://api-platform.com/docs/core/serialization/#using-serialization-groups
https://github.com/typestack/class-validator#validation-groups

Other examples:
https://docs.nestjs.com/techniques/serialization
https://github.com/typestack/class-transformer#skipping-specific-properties, not neeed the other properties.

I don't know if I'm wrong, the only thing I know is that I made a mess, and I was even thinking of using the libraries mentioned above because it was clearer to me.

**Comment by Romakita** [comment]
Hello @chiqui3d,

This is already a work in progress. I working on a new package @tsed/schema. His goals are to solve all issues about models declaration and to be agnostics from @tsed/common package.

To anwsers you over others points:
- Converter has no dependencies from swagger. It's already two sperated things. Decorators from swagger are dedicated to add extra metadata to generate the spec.
   - `@Returns()` and `@ReturnsArray()` have his equivalent on `@tsed/common` package level with `@ReturnType()` decorator. It preferable to use it if you haven't usage of swagger
   - In furture, @tsed/schema will have all of theses decorators to describe JsonSchema, SwaggerSpec and OpenAPI 3
   - Converter won't any longer support validation (like the required decorator or throw error when the model have extra properties). His responsability will be limited to serialization and deserialization. Validation will be performed by AJV (official library used by Ts.ED) or another validator framework like Joi or class-validator.  Today, it's possible to change the validator by overriding the Service and Pipe validation (for now this part is a hidden feature).
- Use `@Serialize()` decorator has no sense. Why ?
   - It does not guarantee that Typescript will return the list of properties to you. In fact, typescript does not list any property if you do not use at least one decorator on the property itself.
   - When you use a `@Property` decorator, it declare automatically a Ts.ED model. It's an equivalent to `@Expose` by definition. If the problem is the name of the decorator. It's possible to create alias :) `@Property() => @Expose` and `@Ignore() => @Exclude()`. But keep in mind, a property not decorated with a Ts.ED decorator is by definition not a deserializable property.
- `@Description()`: I agree this decorator declare automatically a property. But It's logical. If you declare a description for swagger, it means you intend to expose the property. Obviously the validator will see this property. Which is also logical, because this property is an input.

I think the problem the documentation which describe the model declaration with Ts.ED is not enough to understand correctly the final usage of it. I'm open to improve the documentation, if somebody help also to understand what is the pain points and how we can improve it. Also, PR are welcome to improve document. You'd just have to edit Markdown file on github (https://github.com/TypedProject/tsed/edit/production/docs/docs/model.md) and propose your documentation improvment :)

I hope my explaination  helped you :)

See you
Romain

**Comment by chiqui3d** [comment]
Thanks, yes, the real option is to use `@ReturnType(),` I was confused with Swagger.
Everything perfect then, now everything clearer, the only thing I still think, but I can adapt, is that the `Class  `should be shown `completely`, and only have to use `@IgnoreProperty` if you don't want to show a property, independently if you use Swagger decorators or not. 

And about the name I have no problem, it was just what I said before.

Thanks again
