### ISSUE TITLE
[QUESTION] Socket.io return callback with Input decorator

### ISSUE THREAD

**Issue by AmeBitto** [TypedProject/tsed#798]
It is possible to return callback with `@Input` decorator?

```javascript
socket.on('message', (data, callback) => {
  ...
  return callback('ok');
});
```
I need something similar:
```typescript
@Input('message')
onMessage(@Args(0) data: any, @Args(1) callback: () => void) {
  return callback('ok');
}
```

**Comment by Romakita** [comment]
Maybe yes :). Have you tried the example?

**Comment by AmeBitto** [comment]
Yes, i tried `@Input` and `@InputAndEmit`, but it doesn`t work.

**Comment by Romakita** [comment]
Ok. Are you sure it's possible to receive a callback from the front?
Because, @Args forward all received arguments.

Is equivalent to:

```typescript
socket.on('message', (...args) => {
  console.log(args)
});
```
With @tsed:

```typescript
@Input('message')
onMessage(@Args() args: any) {
  console.log(args
}
```
The @tsed/socketio package doesnt' filter arguments. So if the console doesn't show you arg, it means the socketio library doesn't give this args.
For me it's logical, front-end callback cannot be forwarded, you have to use Emit or Broadcast decorator to send response.

See you
Romain

**Comment by ochrstn** [comment]
Front-end callbacks can be forwarded with socketio. But there might be a problem with the Args decorator because this doesn't work:

```ts
@Input('message')
onMessage(@Args(0) data: any, @Args(1) callback: () => void) {
  return callback('ok');
}
```

but the following **does work**:

```ts
@Input('message')
onMessage(@Args(0) data: any, @Args args: any[]) {
  const callback = args[args.length - 1];
  return callback('ok');
}
```

**Comment by Romakita** [comment]
ok I see :)
