### ISSUE TITLE
[QUESTION] Using existing Express app / server

### ISSUE THREAD

**Issue by raphaeljolivet** [TypedProject/tsed#837]
Is it possible to use TSED with an existing Express app ?
I am already using express to serve HTML and static files a don't want to rewrite that part.

I would only want to use it for developing extra REST service. 

It is possible to only develop a bunch on controllers and add setup them on top on my existing app ?

**Comment by Romakita** [comment]
yes it's possible. 

Instead of adding your middleware and routes on express app you have to add it on the Server level.

For example, given this pure express app:

```typescript
const express = require('express')

const app = express();

const router = new Router()
router.get('/', fn);

app.use('/legacy', router);
app.use(express.static('public'))
```
With Ts.ED, it should be implemented as following:
```typescript
const router = new Router()
router.get('/', fn);

@ServerSettings({

})
export class Server extends ServerLoader {
  $afterRoutesInit() {
      this.app.use('/legacy', router)
      this.app.use(express.static('public'))
  }
}
```

> It is possible to only develop a bunch on controllers and add setup them on top on my existing app ?

To be honest, I never tried. Ts.ED create the express app instance. So the solution in this case should be to  give the existing expressApp instance to Ts.ED.

To doing that , you have to override PlatformApplication as follow
```typescript
import myExpressApp from "./legacy-express-app";

@OverrideProvider(PlatformApplication)
export class PlatformExpressApplication extends PlatformApplication {
  constructor(platformHandler: PlatformHandler) {
    super(platformHandler);
    this.raw = myExpressApp
  }
}
```
I'm not sure if it's the best approach but you can try :)

See you
Romain

**Comment by raphaeljolivet** [comment]
Thanks for your help.
I will try this.
