### ISSUE TITLE
[QUESTION] Auth Roles example - req.user property

### ISSUE THREAD

**Issue by vedranjukic** [TypedProject/tsed#857]
In the example on how to implement role based access [https://tsed.io/tutorials/passport.html#roles](https://tsed.io/tutorials/passport.html#roles), `req.user` should contain the authenticated user object.
But when I debug the middleware, on the `req` object, the `user` property is undefined, and the `account` property contains the user object.

```
@Middleware()
export class AcceptRolesMiddleware {
  use(@Req() request: Req & { account: User }, @EndpointInfo() endpoint: EndpointInfo) {
   
    // request.user is undefined
    // if (request.user && request.isAuthenticated()) {

    if (request.account && request.isAuthenticated()) {
      const roles = endpoint.get(AcceptRolesMiddleware)

      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      if (!roles.includes(request.account.role)) {
        throw new Unauthorized('Insufficient role')
      }
    }
  }
}
```

I've tried running the same middleware in the passport example from this repo, with the same behavior.
Although, it's not a big deal, but I just want to make sure that it's not a fault in my code, and will gladly update the example if needed.

**Comment by Romakita** [comment]
The repository example isn't complete, because the way to store user after a login depend on how you want to store the session. It explain why the req.user is empty. This is your responsibility to attach user to the request before all routes according to your implementation choice. There are many ways to store userId (db, sessions, jwt, etc...).

The example should be completed but it means we need to choose a strategy. 
See you
Romain

**Comment by Romakita** [comment]
Look on this example: https://github.com/TypedProject/tsed-passport-jwt-example.git 
It should help you

**Comment by vedranjukic** [comment]
Got it! Thanks!
