### ISSUE TITLE
[BUG] Middleware not being executed before controller handler

### ISSUE THREAD

**Issue by ghmendonca** [TypedProject/tsed#965]
## Information

- **Version:** 5.65.5

The docs shows that the Use decorator is called just before the controller handler:
![Capturar](https://user-images.githubusercontent.com/29390554/95267034-cacc1680-080a-11eb-8f3c-55697b8e6e4e.PNG)

So what I did is I created my middleware
![Capturar](https://user-images.githubusercontent.com/29390554/95267080-dddee680-080a-11eb-9d5b-4ab405b971b4.PNG)

And notice that I left a console log to see if it gets executed.. After that I put the `@Use()` decorator in my route, just like this:
![Capturar](https://user-images.githubusercontent.com/29390554/95267184-07980d80-080b-11eb-9e64-917e0bb44419.PNG)

What I expect to happen is that my middleware would run and after it, my controller handler would run, but right now my middleware is never called and I can see the console.log in my controller handler prints undefined since the `log` variable is set in my middleware.

My `console.log('EXECUTED THIS')` is never called, I also tried using the `UseBefore()` decorator but it doesn't work as well

## Acceptance criteria

- [ ] Middleware should execute before controller handler

**Comment by Romakita** [comment]
@ghmendonca use cannot be used on controller.
Use the @UseBefore instead :)

**Comment by Romakita** [comment]
Hello @ghmendonca 
This is not a bug and I think you've misunderstood how express / Ts.ED resolve middlewares ;)

Your LogMiddleware use `@Err` decorator. This decorator create an express error middleware that is called only if an error occur. This is why your log isn't printed.

I don't understand why you need to create logger. Ts.ED already provide a logger per request and intercept any  error or success response with all request data/response data. Also you can get the current request logger by injecting the Context:

```typescript
@Get('/')
get(@Context() ctx: Context){
   ctx.logger.info({message: 'Hello'}); 
}
```
See https://tsed.io/configuration.html#request-logger . Ts.ED logger is optimized for the production profile because it flush the log after sending the response to the consumer.

If something is missing, I can help you to find a way to cover your needs.

See you
Romain

**Comment by ghmendonca** [comment]
Hi @Romakita 

I see, I didn't know about the `@Err` decorator that doesn't work like that, I think it's missing this piece of information in the docs then.

And I need my on logger since I need to store everything in database, the request, the response and later my services will communicate to another server and I have to store this information as well. I don't really need to print anything, so that's why I am trying to implement some middlewares to store some logs in the database.

I guess I'll have to create two middlewares, one to execute before and another one in case of error right? Or you have a better idea on how I can implement this?

**Comment by Romakita** [comment]
Maybe the interceptor feature is better for your needs :)

**Comment by ghmendonca** [comment]
Yeah, but I would still need a middleware to check the authentication and I would have to implement the log thing there, because if the authentication fail, I have to log that.

I managed to get this working with an ErrorMiddleware which uses the `@Err()` decorator and a LogMiddleware which stores the request data to the database.

@Romakita thanks for your time! If you want to open a new issue to improve the docs around the `@Err()` middleware, I would be glad to push a PR improving it :grin:
