### ISSUE TITLE
Ignore @Property serialize if the value is NULL

### ISSUE THREAD

**Issue by panbhatt** [TypedProject/tsed#976]
When we are creating our @Entity (TYpeORM one) and annotating it with @Property, the value is still being serialized if the value is NULL (in the JSON response via the controller).
Is there is way to prevent that, So that only non-null and not undefined values are being returned from the controller.

**Comment by Romakita** [comment]
Hello @panbhatt,
`null` is considered as a value by JSON and it's normal to serialize it. For example, a price is a number but for a functional reason, sometime the price is not available for a product. We cannot return `0` value to our consumer because, this value means that the product is free, but with `null`, it means the price isn't available. 

I understand you point, the converterService should let you to decide the right serialization approach for the null value.
By using `@OnSerialize`, you can change the `null` by `undefined` (eg: undefined value is serialized by Json).

```typescript
export function CleanNull() {
   return OnSerialize(v => v === null ? undefined : v)
}
```

```typescript
class Model {
  @CleanNull()
  prop: string;
}
```

See you
Romain

**Comment by panbhatt** [comment]
Thanks a lot @Romakita . Appreciate your responses as always.
